version: '3.8'

services:
  # FastAPI Backend
  api:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:ro
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - SERVICE=api
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Streamlit Frontend
  streamlit:
    build:
      context: .
      target: production
    ports:
      - "8503:8503"
    volumes:
      - ./data:/app/data:ro
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - SERVICE=streamlit
    command: [ "streamlit", "run", "app/streamlit_app.py", "--server.port=8503", "--server.address=0.0.0.0" ]
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

  # Development service (optional)
  api-dev:
    build:
      context: .
      target: development
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data:ro
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=development
      - SERVICE=api
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    profiles:
      - dev
    restart: unless-stopped

volumes:
  logs:
